version: "3.7"
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - ./app/front:/app
    env_file:
      - front.env
    ports:
      - "3000:3000"
    tty: true
